name: rem_admin
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # * pick the right locale
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  # * localization
  slang: ^3.7.0
  slang_flutter: ^3.7.0
  localstorage: ^4.0.1+4
  sembast_web: ^2.2.0
  intl: ^0.18.1
  # * fonts
  google_fonts: ^6.1.0
  # * firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_storage: ^11.0.10
  reorderable_grid_view: ^2.2.8
  firebase_crashlytics: ^3.0.10
  firebase_analytics: ^10.1.0
  flutter_staggered_grid_view:
  mapbox_search: ^4.2.0
  # * routing
  go_router: ^11.1.4
  # * state management
  hooks_riverpod: ^2.5.1
  location: ^5.0.3
  geolocator: ^10.1.0
  flutter_hooks: ^0.20.3
  # * annotation
  riverpod_annotation: ^2.3.4
  flutter_easyloading: ^3.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  # * UI utils
  gap: ^3.0.1
  pin_code_fields: ^8.0.1
  dropdown_button2: ^2.3.9
  toastification: ^1.2.0
  # * utils
  age_calculator: ^1.0.0
  quiver: ^3.2.1
  # * KVS
  shared_preferences: ^2.0.16
  # * splash
  flutter_native_splash: ^2.2.16
  # * launcher-icons
  flutter_launcher_icons: ^0.13.1
  # * logger
  roggle: ^0.4.2+1
  # * package info
  package_info_plus: ^4.2.0
  # * image picker
  image_picker: ^1.0.4
  file_picker:
  # * api
  dio: ^5.2.0+1
  flutter_web_frame: ^1.0.0
  cached_network_image: ^3.2.3
#  sidebarx: ^0.16.2
  data_table_2: ^2.3.12
  video_player: ^2.8.2
  google_maps_flutter_web: ^0.5.4+2
  group_button: ^5.2.2
  pagination_flutter: ^0.0.8
  dynamic_color: ^1.6.2
  google_maps_flutter: ^2.5.0
  number_paginator: ^0.4.0
  horizontal_data_table: ^4.3.1
  gradient_borders: ^1.0.0
  socket_io_client: ^2.0.3+1
  sprintf: ^7.0.0
  collection: ^1.18.0
  http_parser: ^4.0.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  # * linter
  pedantic_mono: ^1.20.1
  # * code generator
  build_runner: ^2.3.3
  go_router_builder: ^2.3.3
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  get_storage: ^2.1.1
  riverpod_generator: ^2.3.3
  freezed: ^2.3.2
  recase: ^4.1.0
  json_serializable: ^6.5.4
  slang_build_runner: ^3.7.0

# * flutter_native_splash settings
flutter_native_splash:
  color: "#EEF5F8"
  image: "assets/images/app_icon/splash.png"
  # TODO: Check with the client whether dark mode is necessary.
  color_dark: "#262626"
  image_dark: "assets/images/app_icon/splash.png"
  fullscreen: true
  android_12:
    icon_background_color: "#EEF5F8"
    image: "assets/images/app_icon/splash_android12.png"
    # TODO: Check with the client whether dark mode is necessary.
    icon_background_color_dark: "#262626"
    image_dark: "assets/images/app_icon/splash_android12.png"

# * flutter_launcher_icons settings
flutter_icons:
  image_path: "assets/images/app_icon/app_icon-dev.png"
  android: true
  ios: true
  web:
    generate: true
  macos:
    generate: true
  windows:
    generate: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/app_icon/
    - assets/images/registration/
    - assets/images/bottom_nav/
    - assets/images/mypage/
    - assets/images/background/
    - assets/images/chat/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
