// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVaDLkDFVLLJnd9aAXnWkj7N9FLxdG9rE',
    appId: '1:791575199410:web:fd5e50c8128821465653ab',
    messagingSenderId: '791575199410',
    projectId: 'smoooz-stg',
    authDomain: 'smoooz-stg.firebaseapp.com',
    storageBucket: 'smoooz-stg.appspot.com',
    measurementId: 'G-TY6R80KSYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq_6uUb4i9t9HbXA-CKQv8moAaWfKLhNg',
    appId: '1:791575199410:android:04781c9fd4f66da35653ab',
    messagingSenderId: '791575199410',
    projectId: 'smoooz-stg',
    storageBucket: 'smoooz-stg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL8aUxuytIo_jYGzR5aS5tu8H1BrgPdU0',
    appId: '1:791575199410:ios:56d94678212310915653ab',
    messagingSenderId: '791575199410',
    projectId: 'smoooz-stg',
    storageBucket: 'smoooz-stg.appspot.com',
    iosClientId:
        '791575199410-k94qkpr9ulfg75dqbm7gur49rve03nt2.apps.googleusercontent.com',
    iosBundleId: 'com.example.remAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL8aUxuytIo_jYGzR5aS5tu8H1BrgPdU0',
    appId: '1:791575199410:ios:56d94678212310915653ab',
    messagingSenderId: '791575199410',
    projectId: 'smoooz-stg',
    storageBucket: 'smoooz-stg.appspot.com',
    iosClientId:
        '791575199410-k94qkpr9ulfg75dqbm7gur49rve03nt2.apps.googleusercontent.com',
    iosBundleId: 'com.example.remAdmin',
  );
}
