// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7bJqo481qrkZiU7yFNfLnRlBFQXiDu7s',
    appId: '1:255428335986:web:dd63bd97c1ce1bc60465eb',
    messagingSenderId: '255428335986',
    projectId: 'smoooz-prod',
    authDomain: 'smoooz-prod.firebaseapp.com',
    storageBucket: 'smoooz-prod.appspot.com',
    measurementId: 'G-GQ0LE6ZS9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDimBUJVqHcNNMY5eH2SCwiptdVuyUrAg',
    appId: '1:255428335986:android:dcf9f670b3063d090465eb',
    messagingSenderId: '255428335986',
    projectId: 'smoooz-prod',
    storageBucket: 'smoooz-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7aIlokbqNcob6gaAF5Vxcdc9acxkI1C0',
    appId: '1:255428335986:ios:7934cfe25374a3e10465eb',
    messagingSenderId: '255428335986',
    projectId: 'smoooz-prod',
    storageBucket: 'smoooz-prod.appspot.com',
    iosBundleId: 'com.example.remAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7aIlokbqNcob6gaAF5Vxcdc9acxkI1C0',
    appId: '1:255428335986:ios:7934cfe25374a3e10465eb',
    messagingSenderId: '255428335986',
    projectId: 'smoooz-prod',
    storageBucket: 'smoooz-prod.appspot.com',
    iosBundleId: 'com.example.remAdmin',
  );
}
