// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDnTM_5u04FYEU0pIBdQ5B0vGRqYKbnf6c",
      authDomain: "detect-image-a8ac1.firebaseapp.com",
      projectId: "detect-image-a8ac1",
      storageBucket: "detect-image-a8ac1.appspot.com",
      messagingSenderId: "876518849893",
      appId: "1:876518849893:web:c7d34a2c821e5d2f8ab58c",
      measurementId: "G-QQDYZ4PFV5"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA3bwBXXZcBiDK8dfx2Vztrd1suVLyBq4',
    appId: '1:684178621373:android:19b67f7926bfe663c9c8d4',
    messagingSenderId: '684178621373',
    projectId: 'smoooz-dev',
    storageBucket: 'smoooz-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGHVbfJtnxexhQPzWuHq0IxsZPDt1TOCs',
    appId: '1:684178621373:ios:47b8233e31a61068c9c8d4',
    messagingSenderId: '684178621373',
    projectId: 'smoooz-dev',
    storageBucket: 'smoooz-dev.appspot.com',
    iosClientId: '684178621373-10ec6r39gri7s9s6ve8l98qovo4v18t6.apps.googleusercontent.com',
    iosBundleId: 'com.example.remAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGHVbfJtnxexhQPzWuHq0IxsZPDt1TOCs',
    appId: '1:684178621373:ios:47b8233e31a61068c9c8d4',
    messagingSenderId: '684178621373',
    projectId: 'smoooz-dev',
    storageBucket: 'smoooz-dev.appspot.com',
    iosClientId: '684178621373-10ec6r39gri7s9s6ve8l98qovo4v18t6.apps.googleusercontent.com',
    iosBundleId: 'com.example.remAdmin',
  );
}
